name = "Vanilla"
author = "sammyette"
version = "\\"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a521e440f3f37aaee511606ef45b6ae8cc8c4944a42ac4d7a66b0b23e13f38bc"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
