name = "Vanilla"
author = "sammyette"
version = "\\"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6c8db87a9387a6794c1a1f0547462a7478f7910b770c069eab0584373f4039c"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
