name = "Vanilla"
author = "sammyette"
version = "\\"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59bc023ac320d99dea20e68f39544cff265fc81bb007df4a61dbebd5cab8c026"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
