name = "Vanilla"
author = "sammyette"
version = "\\"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5fe000262b5cf63966cf2d9e391337035cdd05970f0f8a13cc70cdb4ab51ceb"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
