name = "Vanilla"
author = "sammyette"
version = "\\"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53c1a2e4241d285de35a44328f41858c11e77550aaa9b5fe6889e8c2aeb853f9"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
